# Site settings
title: FormFu for Perl
email: your-email@domain.com
url: https://formfu.rocks
description: "Define your forms, don't code them"
keywords: "your keywords, separated by commas"
skills: "Declarative Forms - Data Validation - Open Source - Perl"
meta_author: FormFu Team

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: FormFu Team
  lhs: Code Status
  social: Around the Web
  rhs: About FormFu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/html-formfu
  - title: github
    url: https://github.com/FormFu
  - title: envelope
    url: https://lists.perl.org/list/html-formfu.html

travis:
   - title: HTML::FormFu
     url: https://travis-ci.org/FormFu/HTML-FormFu.svg?branch=master
   - title: Version
     url: https://badge.fury.io/pl/HTML-FormFu.svg
   - title: HTML::FormFu::Catalyst
     url: https://travis-ci.org/FormFu/HTML-FormFu-Catalyst.svg?branch=master
   - title: HTML::FormFu::Element::reCAPTCHA
     url: https://travis-ci.org/FormFu/HTML-FormFu-Element-reCAPTCHA.svg?branch=master
   - title: HTML::FormFu::Imager
     url: https://travis-ci.org/FormFu/HTML-FormFu-Imager.svg?branch=master
   - title: HTML::FormFu::jQuery
     url: https://travis-ci.org/FormFu/HTML-FormFu-jQuery.svg?branch=master
   - title: HTML::FormFu::Model-DBIC
     url: https://travis-ci.org/FormFu/HTML-FormFu-Model-DBIC.svg?branch=master
   - title: HTML::FormFu::Model-LDAP
     url: https://travis-ci.org/FormFu/HTML-FormFu-Model-LDAP.svg?branch=master
   - title: HTML::FormFu::MultiForm
     url: https://travis-ci.org/FormFu/HTML-FormFu-MultiForm.svg?branch=master
   - title: HTML::FormFu::Role::jQueryValidation
     url: https://travis-ci.org/FormFu/HTML-FormFu-Role-jQueryValidation.svg?branch=master
   - title: Catalyst::Controller::HTML::FormFu
     url: https://travis-ci.org/FormFu/Catalyst-Controller-HTML-FormFu.svg?branch=master

# About content
about: 'HTML::FormFu is a HTML form framework which aims to be as easy as possible to use for basic web forms, but with the power and flexibility to do anything else you might want to do (as long as it involves forms).'

# Build settings
markdown: kramdown
permalink: pretty
